[tool.poetry]
name = "cvxcovariance"
version = "0.0.0"             # Don't touch, leave at 0.0.0
description = "..."
authors = ["Kasper", "Thomas"]
readme = "readme.md"
repository = "https://github.com/cvxgrp/cov_pred_finance"
packages = [{include = "cvx"}]

[tool.poetry.dependencies]
python = ">=3.9.0"
pandas = "<2.0.0"
cvxpy = "*"

[tool.poetry.dev-dependencies]
pytest = "7.1.3"
pytest-cov = "*"
seaborn = "*"
arch = "*"
tqdm = "*"
scikit-learn = "*"
matplotlib = "*"
loguru = "*"
plotly = "*"
jupyterlab = "*"


[build-system]
requires = ["poetry>=1.0.2"]
build-backend = "poetry.masonry.api"
